# OS
dist: focal

# Language
language: node_js # node version specified in .nvmrc

# install dependencies
install:
  - npm install

# define environment variables
env:
  global:
    - DOMAIN_TEST=test-domain.brave.coop
    # TWILIO_SID_TEST (from https://www.twilio.com/console/voice/project/test-credentials)
    - secure: 'LQGmKLsk0VcGdt6OyE22FYN+S5ZnNGUNaURyTJZsts3uFoXuK1db3OeLS+xBRF4H1FVjgDtb9KosDwKeUANypbq6SjkhokBNw744WKe9I1gGFVbqh6A/Cpi8PnIj7E86eHsZ3ZNOY/NGZawMVIB9m5HwUaHoTywp08NyLx4ZyLFZ7KnfeJWXNnWiDFmOLHKT52Lm+3F5aZRQG2YsEyl4Zjd/Cbw1SNvuz9WG8Gq8UgsrTtx9eZ0OZhH/gy0SXHk+RCctIfXAbMcsirCzsomcy/N64Dl0QW92yq4eFhIdQrwvQEJWp3JoUDbTibjkWOoYitl1ebiAoDdQdcqvW+ZqxaM8wjMf81Vn56iEOTW+nVhMSpvVfG0664hHuASDI0GG5XcvEHzVBNAQsScDcK9ftN6/Vrbk3PLVc6aayuJviAzDCfkX687gnb+NA0IDlcZd0RMWEPoAXcoXAYM8T1l75E1vbVWF35LKAux5kmyTxDmToXTb50c3c9azmIWuYOJdSkdXI/B8/wvvZieElgSumoIuYLJm+vcwg0hMnxjyb5eVGCJFlYRcUEbzvtwtjAalpQT5xiB+k1FNh3YaR4VJ+T/qiix/CFtli2pUGG7mTj2uo5Y/64qyTne8ZqR/S3+lRo/t5pzf9Hi9seDAOiTlkDna0eYAas9bdKhwhPlLGtU='
    # TWILIO_TOKEN_TEST (from https://www.twilio.com/console/voice/project/test-credentials)
    - secure: 'FPm3qiQofYifPEXpfNEW9ETnU2zASy8l8H63Pt3DurMiuBHJpVJoKXbJeh8OE9UvVnEpZ9yYGkfWxoAQBywcoVEKfdhWgPzlvdBKEH5/Iz8EzGEBst1M1l3OGex/GZYsb8T43ldsdlcE5vLiMLNX8qv6fW/Ye0O66vKE7tebiGvDPXnyXgbCofXPBg5oES37n3E4mQapqas2RGucElQocDmk4BjqUw8KhwU2RzVRhg6qxDqHx116VEm9IsnpwqWl0YwoYzzzkY7jxrE/aCYkwJkufEdS9CxIt9ZXn+WSHBJncPL5HGxjJAwHE5CgPZDZe4ejpYmHW0DBRNGp5Qs6rXU9jVW85DDh582RNryuoqkNH4MGgVYXsesHzFcxlDbJ7VRH4l0GibWAVw4Lq5xoKiiiqW67felfglCENDdngnq8TM5KN8Nw7kDE2hH2yjbMiz3noBKwSIvoNCGJTsM+cKCnt5yCfSe1fgCzJPa8KO18plT6HRUw+dmDXF/yrquIi95UCB/wn4Y+TAosNbJoUE0RARhZNpJe7phDdoMXJI0CGNhzxcLiw3MHSpER1q42j777we2plLlVatbQvf44sVDvRap3J6fsHvfYEcJtgVPrB0LciZqizRIqe/NXunKTO0RRoTz6/QU2yaUmmBebthRuIG2rwb3q1jBFzHthI9w='
    - TWILIO_MESSAGING_SERVICE_SID_TEST=abc123
    - PA_CLIENT_ID_TEST=fakeclientid.apps.googleusercontent.com
    - PA_CLIENT_SECRET_TEST=fakeclientsecret

# Run security audit, linting, unit tests, and integration tests
script:
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npx audit-ci --config ./audit-ci.json; fi
  - npm run lint
  - sudo env "PATH=$PATH" npm run test
