const ALERT_TYPE = {
  BUTTONS_NOT_URGENT: 'BUTTONS_NOT_URGENT',
  BUTTONS_URGENT: 'BUTTONS_URGENT',
  SENSOR_NO_MOTION: 'SENSOR_NO_MOTION',
  SENSOR_DURATION: 'SENSOR_DURATION',
}

module.exports = Object.freeze(ALERT_TYPE)
