const CHATBOT_STATE = {
  STARTED: 'STARTED',
  WAITING_FOR_REPLY: 'WAITING_FOR_REPLY',
  RESPONDING: 'RESPONDING',
  WAITING_FOR_CATEGORY: 'WAITING_FOR_CATEGORY',
  WAITING_FOR_DETAILS: 'WAITING_FOR_DETAILS',
  COMPLETED: 'COMPLETED',
}

module.exports = Object.freeze(CHATBOT_STATE)
