const DEVICE_TYPE = {
  DEVICE_BUTTON: 'DEVICE_BUTTON',
  DEVICE_SENSOR_SINGLESTALL: 'DEVICE_SENSOR_SINGLESTALL',
  DEVICE_SENSOR_MULTISTALL: 'DEVICE_SENSOR_MULTISTALL',
}

module.exports = Object.freeze(DEVICE_TYPE)
