name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOMAIN_TEST: test-domain.brave.coop
      TWILIO_SID_TEST: ${{ secrets.TWILIO_SID_TEST }}
      TWILIO_TOKEN_TEST: ${{ secrets.TWILIO_TOKEN_TEST }}
      TWILIO_MESSAGING_SERVICE_SID_TEST: abc123
      PA_CLIENT_ID_TEST: fakeclientid.apps.googleusercontent.com
      PA_CLIENT_SECRETS_TEST: fakeclientsecret

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        if: github.event_name == 'pull_request'
        run: npx audit-ci --config ./audit-ci.json

      - name: Run Linter
        working-directory: ./server
        run: npm run lint

      - name: Run tests
        working-directory: ./server
        run: npm run test